services:
  app: 
    container_name: RolledMetalProducts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
  postgres_db:
    container_name: RolledMetalProductsPostgresDb
    image: postgres:latest
    environment:
      postgres_user: postgres
      postgres_password: 4567890rtyui7
      postgres_db: RolledMetalProductsPostgresDb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: