version: '3.8'

services:
 traefik:
     image: traefik:v2.9
     command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:81"
     ports:
      - "81:81"
      - "8081:8080"
     volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
     networks:
      - dokploy-network
 app: 
    container_name: RolledMetalProducts
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
    - "3000"
    depends_on:
    - postgres_db
    networks:
    - dokploy-network
    labels:
    - traefik.enable=true
    - traefik.http.routers.app.rule=Host('app.test-test-aaa903-2cee62-192-144-12-119.traefik.me')
    - traefik.http.routers.app.entrypoints=web
    - traefik.http.services.app.loadbalancer.server.port=3000

 postgres_db:
    container_name: RolledMetalProductsPostgresDb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4567890rtyui7
      POSTGRES_DB: RolledMetalProductsPostgresDb
    ports:
     - "5433:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data
    networks:
     - dokploy-network

volumes:
  postgres-data:

networks:
  dokploy-network:
    external: true