version: '3.8'
services:
  app: 
    container_name: RolledMetalProductsTEST
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 8080
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.ourtestdomain.ru`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certResolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
  postgres_db:
    container_name: RolledMetalProductsPostgresDbTEST
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4567890rtyui7
      POSTGRES_DB: RolledMetalProductsPostgresDb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dokploy-network

volumes:
  postgres-data:
  letsencrypt:

networks:
  dokploy-network:
    external: true