version: '3.8'
services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:81"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=wilkak@yandex.ru"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "81:81"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - dokploy-network

  app: 
    container_name: RolledMetalProductsTEST
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 3000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.ourtestdomain.ru`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certResolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
  postgres_db:
    container_name: RolledMetalProductsPostgresDbTEST
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4567890rtyui7
      POSTGRES_DB: RolledMetalProductsPostgresDb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dokploy-network

volumes:
  postgres-data:
  letsencrypt:

networks:
  dokploy-network:
    external: true